.TH DFF "1" "October 2010" "dff version 0.8" "User Commands"
.SH NAME
dff \- A powerfull, efficient and modular digital forensics tool.
.SH SYNOPSIS
.B dff
[\fIoptions\fR]
.SH DESCRIPTION
Digital Forensics Framework
.B dff
is a simple but powerful open source tool with a flexible module system which will help you in your digital forensics works, including files recovery due to error or crash, evidence research and analysis, etc. The source code is written in C++ and Python, allowing performances and great extensibility.

.SH OPTIONS
.TP
\fB\-v\fR      \fB\-\-version\fR
display current version
.TP
\fB\-g\fR      \fB\-\-graphical\fR
launch graphical interface
.TP
\fB\-t\fR      \fB\-\-test\fR=\fINAME\fR
start a specific test
.TP
\fB\-h\fR,     \fB\-\-help\fR
display this help message
.SH "SEE ALSO"
The full documentation for
.B dff
is maintained as a Texinfo manual.  If the
.B info
and
.B dff
programs are properly installed at your site, the command
.IP
.B info dff
.PP
should give you access to the complete manual.
